version: '3.8'

services:
  employee-service-api:
    container_name: employee-service-api
    image: golang:1.22.0-alpine
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    networks:
      - employee-network 
    volumes:
      - ./:/go/app
    depends_on:
      - employee-service-db
    working_dir: /go/app/cmd/server
    command: go run main.go

  employee-service-db:
    container_name: employee-service-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - employee-network  

volumes:
  db_data:

networks:
  employee-network:
    driver: bridge